title: Carlos Alexandre Zgierski # your name (or website title) here
logo: "/images/SukunaP_(Gray).png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>A developing game developer<br>
  I hate Ulysses Monteiro and Artur Nista
  <br><br>
  <a href="https://www.linkedin.com/in/carloszgierski">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
